#!/usr/bin/env python3
"""Unit tests for se-llama generate-presets."""

from __future__ import annotations

import contextlib
import importlib.util
import io
import os
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


REPO_ROOT = Path(__file__).resolve().parents[2]
MODULE_PATH = REPO_ROOT / "snap/local/libexec/generate_presets.py"

spec = importlib.util.spec_from_file_location("generate_presets", MODULE_PATH)
assert spec is not None
generate_presets = importlib.util.module_from_spec(spec)
assert spec.loader is not None
sys.modules[spec.name] = generate_presets
spec.loader.exec_module(generate_presets)


class GeneratePresetsTests(unittest.TestCase):
    def test_renders_active_selected_preset_without_slot_save_path(self) -> None:
        content = generate_presets.render_presets(
            selected_profile="balanced",
            reason="test reason",
        )

        self.assertIn("[balanced]", content)
        self.assertIn("alias = se-llama-balanced", content)
        self.assertIn("load-on-startup = true", content)

    def test_creates_missing_config_directory_and_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            with patch.dict(os.environ, {"SNAP_USER_COMMON": tmp}):
                exit_code = generate_presets.main([])

            target = Path(tmp) / "config" / "presets.ini"
            self.assertEqual(exit_code, 0)
            self.assertTrue(target.exists())
            self.assertIn("[*]", target.read_text(encoding="utf-8"))

    def test_existing_file_is_not_overwritten_without_force(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp) / "config" / "presets.ini"
            target.parent.mkdir(parents=True)
            target.write_text("custom = true\n", encoding="utf-8")

            with patch.dict(os.environ, {"SNAP_USER_COMMON": tmp}):
                exit_code = generate_presets.main([])

            self.assertEqual(exit_code, 0)
            self.assertEqual(target.read_text(encoding="utf-8"), "custom = true\n")

    def test_force_creates_backup_and_replaces_existing_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp) / "config" / "presets.ini"
            target.parent.mkdir(parents=True)
            target.write_text("custom = true\n", encoding="utf-8")

            with patch.dict(os.environ, {"SNAP_USER_COMMON": tmp}):
                exit_code = generate_presets.main(["--force"])

            backups = list(target.parent.glob("presets.ini.backup-*"))
            self.assertEqual(exit_code, 0)
            self.assertEqual(len(backups), 1)
            self.assertEqual(backups[0].read_text(encoding="utf-8"), "custom = true\n")
            self.assertIn(
                "Generated by se-llama.generate-presets",
                target.read_text(encoding="utf-8"),
            )

    def test_generated_comments_contain_editable_fields(self) -> None:
        content = generate_presets.render_presets(
            selected_profile="low",
            reason="test reason",
        )

        self.assertIn("To switch profiles", content)
        self.assertIn("Edit hf-repo, alias, ctx-size, or n-gpu-layers", content)

    def test_selected_profile_is_only_profile_with_load_on_startup(self) -> None:
        content = generate_presets.render_presets(
            selected_profile="large",
            reason="test reason",
        )

        self.assertEqual(content.count("load-on-startup = true"), 1)
        large_section = content.split("[large]", maxsplit=1)[1]
        self.assertIn("load-on-startup = true", large_section)

    def test_creation_output_includes_hf_download_warning(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            stdout = io.StringIO()
            with (
                patch.dict(os.environ, {"SNAP_USER_COMMON": tmp}),
                contextlib.redirect_stdout(stdout),
            ):
                exit_code = generate_presets.main([])

            self.assertEqual(exit_code, 0)
            output = stdout.getvalue()
            self.assertIn("Warning: first se-llama.server start may download", output)
            self.assertIn("llama-server handles downloads at runtime", output)

    def test_auto_selection_memory_thresholds(self) -> None:
        self.assertEqual(generate_presets.select_profile("auto", 8, False).name, "low")
        self.assertEqual(
            generate_presets.select_profile("auto", 12, False).name, "balanced"
        )
        self.assertEqual(
            generate_presets.select_profile("auto", 29, True).name, "balanced"
        )
        self.assertEqual(
            generate_presets.select_profile("auto", 30, True).name, "large"
        )
        self.assertEqual(
            generate_presets.select_profile("auto", 30, False).name, "balanced"
        )

    def test_gpu_detection_returns_bool(self) -> None:
        result = generate_presets.detect_gpu_available()
        self.assertIsInstance(result, bool)

    def test_profile_override_behavior(self) -> None:
        for profile in ("low", "balanced", "large"):
            selected = generate_presets.select_profile(profile, 64, True)
            self.assertEqual(selected.name, profile)


if __name__ == "__main__":
    unittest.main()
